#!/bin/sh
set -e
mkdir /usr/share/zoneinfo
chown default /data
chown default /data/pgsql
head -c 16 /dev/urandom  | sha1sum | cut -c1-10 > /pwfile
echo "PG_PASSWORD=$(cat /pwfile)"
su default -s /usr/bin/initdb -- --pgdata=/data/pgsql --pwfile=/pwfile --username=postgres --auth=trust >/dev/null
echo host all all 0.0.0.0 0.0.0.0 md5 >> /data/pgsql/pg_hba.conf
exec su default -s /usr/bin/postgres -- -D /data/pgsql -c 'listen_addresses=*'
